const Discord = require('discord.js');
const ayarlar = require('../ayarlar.json');
const fs = require("fs");
exports.run = (client, message, params) => {
var Random = [
'**Dans Zamanı** \n İnci Gibi Dişler, İmza Toplayan Adam, Güzelliğe Dair ve NW romanlarıyla tanıdığımız Zadie Smith bu kez güçlü bir bildungsroman (gelişim romanı) örneğiyle karşımızda: Dans Zamanı. Smith’in tüm hikayesini isimsiz bir anlatıcının dilinden anlattığı bu roman aynı dans kursuna giden iki küçük kızın yıllara yayılan arkadaşlığı ve çatışmasını kıvrak bir dille sunuyor. Zadie Smith okurlarının aşina olduğu azınlık olmak, yurtsuzluk, aidiyet, fırsat eşitsizliği gibi konular etrafında gezinen roman Londra’nın varoşlarında gezinmekle kalmıyor, Afrika’nın köylerine dek uzanıyor. Roman, zeki fakat özgüvensiz anlatıcının yetenekli ve kendinden emin arkadaşı karşısında uğradığı işkenceyi gözler önüne serişiyle Elena Ferrante hayranlarına da göz kırpıyor. Finaliyle bildik kalıpların dışına çıkan ve başarı ve mutluluk arasındaki ilişkiyi sorgulatan Dans Zamanı ırk, sınıf ve cinsiyete dair ayrımları da olduğu gibi, tüm çıplaklığıyla gözler önüne seren bir roman. Dili ustalıkla kullanan Zadie Smith’in bu romanıyla bu yılki Man Booker Ödülü finalistleri arasında yer aldığını da eklemeden geçmeyelim!',
'**Süslü Hatıralar Sahnesi** \n Okurun Değmez, Çıt Yok, Sincap ve Hatırla gibi romanlarıyla tanıdığı yazar İsmail Güzelsoy bu kez kendisi ve abisinin ilişkisinden ilhamla ortaya çıkardığı iki kardeşle, Recep ve Erdal’la tanıştırıyor bizleri. Aslında onlara iki kardeş demek bile onların arasındaki ilişkiye haksızlık etmek olabilir, zira onlar adeta tek bedende yaşayan iki ruh, bir bozuk paranın aynı madeni paylaşan iki yüzü gibi! Bir kamyonetin kasasında, İstanbul’a doğru yapılan bir yolculukla başlayan hikaye bütün bir ömrü içine alacak kadar da geniş.',
'**Sonbahar** \n Karl Ove Knausgaard ismi çok satanlar listelerinden inmese de, o bildiğimiz “yıldız yazar”lardan, spot ışıklarının altında olmak için doğmuş popüler figürlerden değil. Norveçli yazar istese de istemese de, Kavgam adlı otobiyografik serisiyle 2000’lerin en önemli edebiyat fenomenlerinden birine dönüştü. Eleştirmenlerin bir kısmı onun gündelik hayatın sıkıcı ve fuzuli denebilecek ayrıntılarını tasvir edişini yenilikçi ve taze bulurken, bir kısmı da ifşacılıkla, ucuz edebiyat yapmakla eleştirdi yazarı.',
'**Misafir** \n Bir akıl hastanesi düşünün ki adı “Ev” olsun. Üstelik burada kimseye de deli denmiyor, herkes “Misafir.” Bütün hemşire ve hastabakıcılar abi ve abla, başhekim ise Baba. Üstelik Ev’in dışındakiler bir bakıma içeridekilerden daha deli!',
'**Feminist Dövüş Kulübü** \n Hangimiz tepemizdeki cam tavana en az bir kez toslamadık? Hangimiz erkeklerle girdiğimiz kariyer yarışında birilerinin eteğimize yapışıp bizi geri çektiğini hissetmedik? Gelin açık konuşalım; hangimiz, öyle ya da böyle, iş hayatında ayrımcılığa maruz kalmadık.',
'**Flamingolar Pembedir** \n Annesiz kalmak bir kız çocuğunu nasıl değiştirir? Aslı Perker işte bu sorunun peşine düşüyor ve Flamingolar Pembedir ile “alternatif” hayat hikayesini paylaşıyor okurlarıyla.',
'**Nohut Oda** \n Melisa Kesmez’in üçüncü öykü derlemesi Nohut Oda geçtiğimiz günlerde Sel Yayıncılık tarafından yayımlandı. Atları Bağlayın Geceyi Burada Geçireceğiz ve Bazen Bahar’ın ardından Melisa Kesmez okura eski bir dostuyla karşılaşmışçasına bir aşinalık duygusu yaratan naif üslubunu Nohut Oda ile de sürdürüyor.',
'**Bin Yıllık Hemşehri** \n Bir gelincik kaç yıl yaşar dersiniz? En fazla beş ya da altı sene. Fakat bu ortalama görüp görebileceğiniz en ilginç gelincik olan Theo’yu kapsamıyor elbette!',
'**Nasıl Oldu Da Kitap Yazdım** \n Hiç yazar olmayı hayal ettiniz mi? Okul defterlerine yazılmış öyküleriniz ya da romanlarınız oldu mu mesela? Yahut “Keşke zamanında bana da yol gösterecek biri olsaydı!” diye hayıflandığınız olur mu? Merak etmeyin, hiçbir şey için geç değil! Annet Huizing imzalı Nasıl Oldu Da Yazar Oldum sadece gençlere değil, her yaştan yazar adayına rehberlik edebilecek nitelikte bir kitap.',
'**Kedi Gibi** \n Stéphane Garnier’in çok satan kitabı Kedi Gibi Düşünmek ve Davranmak, kedilere dair söylenmiş veciz sözler eşliğinde, bu nev-i şahsına münhasır varlıkların “hayat duruşları”yla bize yaşamımızda nasıl kılavuzluk edebileceğine ışık tutarken kedilerle bu dünyayı paylaşmanın keyfini de hatırlatıyor. Bir yaşam koçu gibi bize ne yapıp ne yapmamamız gerektiğini söyleyen kişisel gelişim kitaplarından biri değil Kedi Gibi. Evlerimizi, yaşam alanlarımızı bizimle paylaşan tüylü dostlarımızın karakterini çözümlüyor, bunu yaparken de, bize hayatta karşımıza çıkacak pürüzlerle nasıl baş edebileceğimizi fısıldıyor. Douglas Adams’ın o meşhur nasihatındaki gibi “paniğe kapılmayın” diyor aslında kitap bir nevi; evren kocaman ve yaşam hayli zorlu, ancak bu dünyada yaşayan başka varlıkları iyi incelersek, onlardan çok şey öğrenebiliriz. Kolay okunan metni ve zekice hazırlanmış bölümleriyle, kedi sevgisiyle edebiyat sevgisinin kesişiminde yer alan bir kitap bu. Hemingway, Mallarmé, Montaigne, René Char gibi isimlerin yazdıklarından alıntılarla, kedilerin tarihin pek çok önemli figürüne nasıl ilham kaynağı olduğunu görüyoruz ve sokakta karşımıza çıkan ilk dört ayaklıya farklı gözle bakıyoruz.',
'**Rakun** \n Suat Duman Dünyanın Leşleri’nin ardından yeni bir macera ile sahalara geri döndü! Pulp Fiction türüne göz kırpan Rakun’da bir Picasso rulosunun peşine takılan okuru hayal gücünün sınırlarını zorlayacak bir kurgu bekliyor.',
'**Eski Mısır** \n Dünya tarihine ilgi duyan okurlar, bu konuyla ilgili genellikle bu konudaki kitapların ikiye ayrıldığına tanık olurlar: araştırma kitapları ve tarihi romanlar... Araştırmacı, tarihi neden-sonuç ilişkisine göre yorumlamayı seven okurlar için kurguyla örülmüş tarihi romanlar çok cezbedici gelmeyebilir; kurgu seven tarihî roman okurları için de tarih konulu makaleler ve araştırma yazıları yorucu ve anlaşılması güç metinler olarak gelebilir. 1969 doğumlu İngiliz Mısır Bilimci ve akademisyen Toby Wilkinson, her iki sorunu ustalıkla ortadan kaldırıyor ve tabiri caizce "Roman Gibi Okunan Araştırma Kitabı" çıkıveriyor ortaya...',
'**Genç Yazarlar İçin Hikaye Anlatıcılığı Kılavuzu** \n İstanbul Bilgi Üniversitesinde Yazarlık Teknikleri Atölyeleriyle ve daha çok polisiye romanlarıyla tanıdığımız yazar Celil Okerin etkileyici hikaye anlatım tekniğinin sırrını keşfetmek isteyen genç yazar adayları için en ilham verici kitaplardan biri.',
'**Macbeth - Jo Nesbo** \n İngilterede Hogarth yayınevinin başlattığı "Shakespeare Yeniden" serisi, iki yeni kitapla Türkçede devam ediyor. Shakespearein ölümünün 400. yılı kapsamında hayata geçirilen "Shakespeare Yeniden", günümüz yazarlarına Shakespeare metinlerini "yeniden" yazdırıyor. ',
'**Unutmanın Genel Teorisi** \n Angolada yaşayan, Portekizce yazan bir gazeteci José Eduardo Agualusa. Portekiz ve Brezilya kökenlerine sahip bir yazar olarak, Angola tarihine dair yazdıkları, ülkenin sömürgeciliğe karşı yıllar süren direnişini dünyanın geri kalanına aktarma konusunda önemli. ',
'**Güç** \n Bir gün güç el değiştirse ne olur? Hele de erkeklerin üstünlüklerini konuşturmayı pek sevdikleri o fiziksel güç? Dünya gerçekten de yerinden oynar mı? Naomi Alderman kendisine dünya çapında bir şöhret kazandıran romanı Güç’te tam da bu tür bir güçten bahsediyor işte.',
'**Artemis** \n Andy Weir’in kaleminden çıkan Marslı sadece uluslararası bir çoksatar haline gelmekle kalmadı, yayıncılık dünyasında da yepyeni bir dönemin kapısını açtı. Zira enteresan bir bilimkurgu olan Marslı gönderildiği tüm yayıncılar tarafından reddedilmiş, Andy Weir ise çözümü romanını kendi web sitesinde yayınlamakta bulmuştu. Marslı okur nezdinde öyle çok sevildi ki yayıncıların ilgisini de kaçınılmaz olarak çekti. Bu yolda Marslı başrolünde Matt Damon’ın yer aldığı bir sinema filmine de dönüştü.',
'**Sessiz Kalma!** \n Sessiz kalmaman gereken durumlarda sesini çıkarmayacaksan sesin olmasının ne anlamı var? Angie Thomas imzalı Sessiz Kalma! işte tam olarak bu soruya odaklanıyor. Destansı bir kahramanlık hikayesi değil, gerçekçi bir değişim ve dönüşüm hikayesi Starr Carter’ınki.',
'**Köpek Gibi Büyütülmüş Çocuk** \n Bruce Perry kendimize söylediğimiz bu sıradan yalanları acımasızca yüzümüze çarpıyor. Koridor Yayınları’ndan çıkan Köpek Gibi Büyütülmüş Çocuk, güncel baskısıyla herkesin kütüphanesinde önemli bir yer tutacak gibi görünüyor. Sadece psikologların ve psikiyatristlerin değil, çevresinde çocuklar olan ya da olmasını planlayan herkesin ilgisini çekeceğine şüphe yok.',
'**Yeraltı Demiryolu** \n Geçtiğimiz yılın en çok konuşulan kitaplarından biri Yeraltı Demiryolu, kuşkusuz. Colson Whitehead’in gerek ödüllere, gerekse adaylıklara doğmayan romanı her ne kadar fantastik bir havada geçse de son derece gerçekçi bir sorunu deşiyor: Kölelik.',
'**Yarım Kalan Bazı Aşklar** \n Düşünün ki anneniz ölmüş, sanki bir daha hiç sevilmeyeceksiniz. Beş aydır bir kez olsun başınızı yastığa koyamamışsınız. Hayatınız sonu gelmeyen bir işkence haline gelmiş. Gecenin karanlığı kabus gibi üstünüze çökmüş ve en büyük korkularınızdan kaçarken bulmuşsunuz kendinizi. Tam da her şey bitti dediğinizde, sokağın ortasına yığılıp kalmışsınız ve gözlerinizi bir daha hiç açmamayı umarak kapatmışsınız. Siz, Zeynep’mişsiniz. Tanımadığınız bir evde, tanımadığınız bir yatakta, tanımadığınız bir sevecenlikte gözlerinizi açtığınızda ve karşınızda Arda’nın olanca sıcaklığını bulduğunuzda, siz ne yapardınız?'
];
var sözver = Math.floor(Math.random()*Random.length);
const söz = new Discord.RichEmbed()
.setDescription(`${Random[sözver]}`)
.setColor(0xe2ff00)
message.channel.send(söz)
};
exports.conf = {
enabled: true,
guildOnly: false,
aliases: ['Kitapöneri, kitapöneri, kitaponeri, Kitaponeri'],
permLevel: 0
};

exports.help = {
name: 'kitapöneri',
description: 'kitapöneri',
usage: 'kitapöneri'
};